### ISSUE TITLE
Bulk Insert: TypeError: value is out of bounds

### ISSUE THREAD

**Issue by woverton** [SAP/node-hdb#10]
When launching a bulk insert with 1000 rows, I sometimes get this error. I am assuming a piece of data I am putting in is causing this issue. Is there anyway to show the user a better message? possibly containing the offending row?

TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:705:11)
    at Buffer.writeInt32LE (buffer.js:782:5)
    at Writer.writeInt [as 3](/project/node_modules/hdb/lib/protocol/Writer.js:382:10)
    at Writer.add (/project/node_modules/hdb/lib/protocol/Writer.js:90:15)
    at Writer.setValues (/project/node_modules/hdb/lib/protocol/Writer.js:57:10)
    at next (/project/node_modules/hdb/lib/protocol/ExecuteTask.js:161:21)
    at ExecuteTask.getParameters (/project/node_modules/hdb/lib/protocol/ExecuteTask.js:177:3)
    at ExecuteTask.sendExecute (/project/node_modules/hdb/lib/protocol/ExecuteTask.js:184:8)
    at execute (/project/node_modules/hdb/lib/protocol/ExecuteTask.js:74:10)
    at ExecuteTask.run (/project/node_modules/hdb/lib/protocol/ExecuteTask.js:112:3)

**Comment by woverton** [comment]
After a lot of playing around, I discovered that I was trying to put an int that was too big for the column into HANA. A nicer error message would still be nice.

**Comment by holgerkoser** [comment]
This has nothing to do with HANA. The exception is raised by the Buffer implementation. You will get same error if you do the following.
```js
new Buffer(4).writeInt32LE(2147483648, 0);
```
Also gives the same error.
```
TypeError: value is out of bounds
    at TypeError ()
    at checkInt (buffer.js:705:11)
    at Buffer.writeInt32LE (buffer.js:782:5)
```

**Comment by holgerkoser** [comment]
Create issue [Improve error handling for prepared statements and bulk insert](#23) for tracking the enhancement.
