### ISSUE TITLE
SAP/hana-client architecture issue

### ISSUE THREAD

**Issue by TalShorSap** [SAP/node-hdb#207]
Hi, im trying to run our node-sbf project and i fail during the npm install phase on the following issue:

 FATAL ERROR: A fatal error occurred during install.
npm ERR! dlopen(/Users/i563212/go/src/node-sbf/node_modules/@sap/hana-client/prebuilt/darwinintel64-xcode7/hana-client.node, 0x0001): tried: '/Users/i563212/go/src/node-sbf/node_modules/@sap/hana-client/prebuilt/darwinintel64-xcode7/hana-client.node' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

Can you please help? thanks :)

**Comment by cplussharp** [comment]
This is SAP/node-hdb and not SAP/hana-client.
But your problem might be that the hana-client does not yet  support Apples M1 chip.

**Comment by jeffalbion** [comment]
Hello,

This support has now been officially released to customers with the 2.14.18 driver to [npm](https://www.npmjs.com/package/@sap/hana-client).

Best regards,
Jeff

**Comment by Showkath** [comment]
> Hello,
> 
> This support has now been officially released to customers with the 2.14.18 driver to [npm](https://www.npmjs.com/package/@sap/hana-client).
> 
> Best regards, Jeff

Hi Jeff,

Thanks for your support .

I am using M1 MAC  & installed 
npm = 8.19.2
node = v18.11.0

when i ran    npm install @sap/hana-client.

I am getting below error , i also verified proxy settings 

npm ERR! FetchError: request to https://registry.npmjs.org/array.prototype.map/-/array.prototype.map-1.0.5.tgz failed, reason: connect ECONNREFUSED 10.236.200.180:8081
npm ERR!     at ClientRequest.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at onerror (/opt/homebrew/lib/node_modules/npm/node_modules/agent-base/dist/src/index.js:117:21)
npm ERR!     at callbackError (/opt/homebrew/lib/node_modules/npm/node_modules/agent-base/dist/src/index.js:136:17)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!  FetchError: request to https://registry.npmjs.org/array.prototype.map/-/array.prototype.map-1.0.5.tgz failed, reason: connect ECONNREFUSED 10.236.200.180:8081
npm ERR!     at ClientRequest.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at onerror (/opt/homebrew/lib/node_modules/npm/node_modules/agent-base/dist/src/index.js:117:21)
npm ERR!     at callbackError (/opt/homebrew/lib/node_modules/npm/node_modules/agent-base/dist/src/index.js:136:17)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '10.236.200.180',
npm ERR!   port: 8081,
npm ERR!   type: 'system'
npm ERR! }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'


----------------------------

I also tried to explicitly tried to install  "npm i array.prototype.map "

Any suggestion or do i need to downgrade npm/nodejs

**Comment by jeffalbion** [comment]
Hello, your issue seems to be a networking issue: your host can't reach '10.236.200.180' (a local network address?) from your network.

Also, this issue is not relevant to @sap/hana-client since we do not rely on or interact with the https://www.npmjs.com/package/array.prototype.map module.
