### ISSUE TITLE
'RangeError: Maximum call stack size exceeded' during large insert

### ISSUE THREAD

**Issue by woverton** [SAP/node-hdb#21]
Large insert (1000+ rows) causing errors

```
RangeError: Maximum call stack size exceeded
    at ExecuteTask.end (/var/node/wo/Convertiq/node_modules/hdb/lib/protocol/ExecuteTask.js:115:41)
    at done (/var/node/wo/Convertiq/node_modules/hdb/lib/protocol/ExecuteTask.js:53:10)
    at finalize (/var/node/wo/Convertiq/node_modules/hdb/lib/protocol/ExecuteTask.js:59:14)
    at receive (/var/node/wo/Convertiq/node_modules/hdb/lib/protocol/ExecuteTask.js:76:16)
    at send (/var/node/wo/Convertiq/node_modules/hdb/lib/protocol/ExecuteTask.js:186:14)
    at next (/var/node/wo/Convertiq/node_modules/hdb/lib/protocol/ExecuteTask.js:163:16)
    at handleParameters (/var/node/wo/Convertiq/node_modules/hdb/lib/protocol/ExecuteTask.js:152:5)
    at done (/var/node/wo/Convertiq/node_modules/hdb/lib/protocol/Writer.js:196:5)
    at next (/var/node/wo/Convertiq/node_modules/hdb/lib/protocol/Writer.js:166:14)
    at Writer.finializeParameters (/var/node/wo/Convertiq/node_modules/hdb/lib/protocol/Writer.js:184:3)
```

My Code (ish):
```
var sql = 'insert into "' + databaseName.toUpperCase() + '"."' + tableName + '" values (' + columns + ')';

this.connections[sessionID].prepare(sql, function(err, statement) {

    if(err) throw err;

    var insertData = [];

    for (var i = data.length - 1; i >= 0; i--) {
        insertData.push(data[i])
    }

    statement.exec(insertData, function(err, affectedRows) {
        debug(err, 'Amount of affected rows: ' + affectedRows.length);
    });
});
```

Hana Version/Status:
```
SELECT * FROM SYS.M_DATABASE

SYSTEM_ID | DATABASE_NAME | HOST | START_TIME | VERSION | USAGE
- - - - - - - - - - - - - - - - - - - 
M1D | M1D | prd-nohana01 | 2015-08-19T14:53:45.932 | 1.00.097.01.1436865239 | DEVELOPMENT

> \st

HOST | HOST_ACTIVE | HOST_STATUS
- - - - - - - - - - - - - - - - - - - 
prd-nohana01 | YES | OK
```

**Comment by holgerkoser** [comment]
From your code snippet I am not able to see what is the sql command e.g. the value of ```columns```. It should be something like "?" or "?, ?, ?". I also do not see what is the variable ```data```. Is it an Array of Arrays or is it an Array of single values.

**Comment by woverton** [comment]
Thanks :+1:
