### ISSUE TITLE
Error: "hdb" couldn't be found

### ISSUE THREAD

**Issue by SovithKothari** [SAP/node-hdb#223]
Hi team,

We are trying to move our existing Docker container to distroless container method. 
In local, we are able to build the image and run the container but when we push it to our repo, our kyma k8s deployment pod is crashing.

Error:
```
[cds] - loading server from { file: 'srv/server.js' }
[utility] - Enter-UtilityService-Constructor()
[server] - [CDS][Event][BOOTSTRAP]
[cds] - loaded model from 18 file(s):
srv/server.cds
db/common.cds
app/services.cds
srv/api/v2/dataCenterService.cds
srv/api/v1/dataCentersService.cds
srv/api/v1/dataCenterService.cds
srv/api/v1/dataCenterMonitorService.cds
srv/api/common-apis/masterDataService.cds
srv/api/common-apis/flexiConfiguration.cds
srv/api/common-apis/decisionTree.cds
app/datacenter/annotations.cds
app/cloud_service/annotations.cds
app/admin/annotations.cds
srv/api/api.cds
srv/health/health.cds
db/data-model.cds
db/API-schema/API-response.cds
node_modules/@sap/cds/common.cds
/app/node_modules/@sap/cds/libx/_runtime/hana/driver.js:198
throw new Error(`"${name}" could not be found. Please make sure it is installed.`)
^
Error: "hdb" could not be found. Please make sure it is installed.
at _getHanaDriver (/app/node_modules/@sap/cds/libx/_runtime/hana/driver.js:198:13)
at Object.<anonymous> (/app/node_modules/@sap/cds/libx/_runtime/hana/driver.js:205:18)
at Module._compile (node:internal/modules/cjs/loader:1376:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
at Module.load (node:internal/modules/cjs/loader:1207:32)
at Module._load (node:internal/modules/cjs/loader:10
at Module.require (node:internal/modules/cjs/loader:1235:19)
at require (node:internal/modules/helpers:176:18)
at Object.<anonymous> (/app/node_modules/@sap/cds/libx/_runtime/hana/pool.js:5:14)
at Module._compile (node:internal/modules/cjs/loader:1376:14)
Node.js v20.10.0
```

We have all the dependencies and packages in our package.json and we are also able to verify it in our local running container but in our kyma k8s pod, it says that it is not able to find the hdb package.

link: https://github.tools.sap/Unified-Provisioning/optimal-dc-selection/pull/649/files

Kindly help us in understanding and fixing this issue
Please let me know if you need any additional resource(s)/help

**Comment by SovithKothari** [comment]
link to image (jfrog repo): https://common.repositories.cloud.sap/ui/native/clm-am-btp-docker/com.sap.clm.am.btp/dc.selection/1.0.0-20231220051033_099130dd89590a6f93868e2a72d9274a0d1d98cf/

**Comment by gregorwolf** [comment]
Are aware that the links you've provided are pointing to SAP internal repositories?

**Comment by SovithKothari** [comment]
Hi @gregorwolf , 

Yes i am aware about it and  the reason for doing so is my colleague raised an issue before(link mentioned below). They were asking steps to reproduce the issue locally. The point is that it is working perfectly in local but it is causing issue in our kyms k8s dev environment. So, now i have to share the exact reference links here to help you understand the issue better and help us.

previous issue ticket link: https://github.tools.sap/cap/issues/issues/14639

Best regards,
Sovith

**Comment by gregorwolf** [comment]
Have you looked inside the created container if the hdb packages exists in the node_modules folder?

**Comment by SovithKothari** [comment]
Hi @gregorwolf ,

Yes, it is present in package.json dependency and even while running the local docker container, i looked into the node_modules and i was able to see the hdb packages and related folders.

Best Regards,
Sovith

**Comment by SovithKothari** [comment]
Hi @gregorwolf can you please help us here?
