### ISSUE TITLE
SQL parsing bug causes syntax error

### ISSUE THREAD

**Issue by woverton** [SAP/node-hdb#28]
```
> SELECT TABLE_NAME, CONCAT(CONCAT('"', STRING_AGG(COLUMN_NAME, '","')), '"') FROM (SELECT TABLE_NAME, COLUMN_NAME FROM SYS.CONSTRAINTS WHERE SCHEMA_NAME='MY_SCHEMA' ORDER BY "POSITION") GROUP BY TABLE_NAME

undefined:4
"CONCAT(CONCAT('"',STRING_AGG(COLUMN_NAME,'","')),'"')": this.readString()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at Function (native)
    at createEvilParseFunction (/home/woverton/Documents/Repositories/censql/node_modules/hdb/lib/protocol/Parser.js:149:10)
    at Parser.createParseFunction (/home/woverton/Documents/Repositories/censql/node_modules/hdb/lib/protocol/Parser.js:50:12)
    at Parser.createParseRowFunction (/home/woverton/Documents/Repositories/censql/node_modules/hdb/lib/protocol/Parser.js:36:15)
    at Parser.createTransform (/home/woverton/Documents/Repositories/censql/node_modules/hdb/lib/protocol/Parser.js:71:38)
    at ResultSet.createParser (/home/woverton/Documents/Repositories/censql/node_modules/hdb/lib/protocol/ResultSet.js:198:39)
    at ResultSet.createArrayStream (/home/woverton/Documents/Repositories/censql/node_modules/hdb/lib/protocol/ResultSet.js:224:52)
    at ResultSet.fetch (/home/woverton/Documents/Repositories/censql/node_modules/hdb/lib/protocol/ResultSet.js:144:21)
    at next (/home/woverton/Documents/Repositories/censql/node_modules/hdb/lib/protocol/Result.js:226:19)
    at fetchAll (/home/woverton/Documents/Repositories/censql/node_modules/hdb/lib/protocol/Result.js:228:3)
```

Not too sure what is going on here. It just really doesn't like it when I run that query.

**Comment by woverton** [comment]
I should note that the query works fine in HANA Studio.

**Comment by holgerkoser** [comment]
The problem in the creation of the function body of the parse row function. 
https://github.com/SAP/node-hdb/blob/master/lib/protocol/Parser.js#L165

It should be
```js
 function addPairToRow(column) {
    return JSON.stringify(column.key) + ': this.' + getReadFunction(column);
  }
```

As a workaround I recommend to change query into something like:
```
SELECT 
  TABLE_NAME, 
  CONCAT(CONCAT('"', STRING_AGG(COLUMN_NAME, '","')), '"') AS COL_NAME 
FROM (
  SELECT TABLE_NAME, COLUMN_NAME 
  FROM SYS.CONSTRAINTS WHERE SCHEMA_NAME='MY_SCHEMA' ORDER BY "POSITION"
) GROUP BY TABLE_NAME
```

The column.key in this case is COL_NAME and does not contain double quotes.

**Comment by woverton** [comment]
Sadly my application allows users to enter their own queries. Is there any other work around or will I have to instruct users to always use 'AS'?

**Comment by holgerkoser** [comment]
Until I find some time to fix it you could try to use `honestParseFunction` which is much slower from the performance point of view but works in the case you are using node-hdb in chrome apps. To force node-hdb to use the `honestParseFunction` you have to set 
```js
process.browser = true;
```
somewhere in you application.

**Comment by woverton** [comment]
```process.browser = true;```

worked a charm. Thanks

**Comment by woverton** [comment]
Also, I'm not using chrome apps, I'm making a cli tool for SAP HANA, [CenSQL](https://www.npmjs.com/package/censql).

**Comment by holgerkoser** [comment]
Yes. Of course. But this is currently the only way not to use the Function constructor which creates a new Function object from a string. 

CenSQL is a very nice and helpful! May be it makes no sense but couldn't it also build as chrome app? Have you seen https://github.com/SAP/node-hdb/wiki/Develop-Chrome-Apps-for-SAP-HANA?

**Comment by holgerkoser** [comment]
I will keep this issue open until a have released the fix.

**Comment by woverton** [comment]
@holgerkoser You may be interested in a little test project of mine using node-webkit to create a standalone application using node-hdb: https://github.com/Centiq/CenSQL-Studio

**Comment by holgerkoser** [comment]
@woverton 
http://nwjs.io/ :+1: 
_New! Beta version of 0.13.0 supports Chrome App now!_ 
Thank you.

**Comment by woverton** [comment]
Oh right! I'll have a play later :+1:
