### ISSUE TITLE
SQL statement CONNECT fails with Error: Invalid or unsupported FunctionCode

### ISSUE THREAD

**Issue by dotchev** [SAP/node-hdb#46]
SQL
```
CONNECT new_user PASSWORD Password1
```
Error stack
```
     Error: Invalid or unsupported FunctionCode
      at Result.handle (node_modules/hdb/lib/protocol/Result.js:104:11)
      at handleReply (node_modules/hdb/lib/Client.js:236:12)
      at receive (node_modules/hdb/lib/util/Queue.js:113:18)
      at Connection.receive (node_modules/hdb/lib/protocol/Connection.js:341:3)
      at Socket.ondata (node_modules/hdb/lib/protocol/Connection.js:216:12)
      at readableAddChunk (_stream_readable.js:153:18)
      at Socket.Readable.push (_stream_readable.js:111:10)
      at TCP.onread (net.js:531:20)
```
hdb@0.6.0

**Comment by holgerkoser** [comment]
This kind of SQL statement is with the current version not supported. I assume returned FunctionCode is `14`.

https://github.com/SAP/node-hdb/blob/master/lib/protocol/common/FunctionCode.js#L31

Pull request for supporting this FunctionCode are welcome :-)
