### ISSUE TITLE
Cannot read property 'createTask' of undefined when closing connection early

### ISSUE THREAD

**Issue by ktravelet** [SAP/node-hdb#74]
I'm using async.waterfall similar to your examples to create client -> connect -> execute -> disconnect.

In the execution function, before the actual execution, there is a timer for 10 sec.  If the timer hits before the query returns, the callback is called to the client.disconnect.

Shortly after the error for the 10 sec limit, an uncaught error is emitted from the HDB driver and crashes the server.

The error and code below.

Any workaround or way to catch the error would be much appreciated.

Thanks!
```

TypeError: Cannot read property 'createTask' of undefined
    at Connection.enqueue (/data/rootdir/home/i827087/Projects/Hanamon/node_modules/hdb/lib/protocol/Connection.js:366:30)
    at Connection.fetchNext (/data/rootdir/home/i827087/Projects/Hanamon/node_modules/hdb/lib/protocol/Connection.js:487:8)
    at ResultSet.sendFetch (/data/rootdir/home/i827087/Projects/Hanamon/node_modules/hdb/lib/protocol/ResultSet.js:282:20)
    at ResultSet.resume (/data/rootdir/home/i827087/Projects/Hanamon/node_modules/hdb/lib/protocol/ResultSet.js:130:15)
    at Readable._read (/data/rootdir/home/i827087/Projects/Hanamon/node_modules/hdb/lib/util/index.js:224:8)
    at Readable.read (_stream_readable.js:348:10)
    at flow (_stream_readable.js:761:34)
    at ResultSetTransform.<anonymous> (_stream_readable.js:623:7)
    at emitNone (events.js:86:13)
    at ResultSetTransform.emit (events.js:185:7)

```

```
async.waterfall([

    // Create client connection
    (callbackWF) => {

        var client = hdb.createClient({

            host: host,
            port: port,
            user: user,
            password: password

        });

        callbackWF(null, client);

    },

    // Connect the client
    (client, callbackWF) => {

        client.connect( (err) => {

            if (err) {

                console.log("Error while connecting to client, " + name +  ". " + err);
                return callbackWF(1, client);

            }

                return callbackWF(null, client);

        });
    },

    // Get data for table.
    (client, callbackWF) => {

        client.on('error', function (err) {

            console.error('HANA HDB Error: ', err);

        });

        var timer = setTimeout(function() {

            console.log(name + " " + host + " did not return statement within 10,000ms. Statement: " + select);
            callbackWF(1, client);
            return clearTimeout(timer);

        }, 10000);

        client.exec(select, {rowsAsArray: true}, (err, rows) => {

            clearTimeout(timer);

            if (err) {

                console.log("Error while getting data from " + name +  " table: " + table + ". " + err + select);
                return callbackWF(1, client);

            } else {

                if (rows.length == 0) {
                    
                    client.exec(<another select>, {rowsAsArray: true}, (err, emptyRows) => {

                        if (err) {

                            console.log("Error sending empty tables: " + err);

                        } else {

                            <Do stuff with data>

                        }

                    });

                }


                <Do stuff with data>

            }

                callbackWF(null, client);

        });

    }

], (err, client) => {

    client.disconnect();

});
```

**Comment by alexpenev-s** [comment]
Which version of the driver do you use?

**Comment by ktravelet** [comment]
npm ls | grep hdb
+-- hdb@0.10.0

**Comment by ktravelet** [comment]
I just upgraded to 0.12.0 and received the same error with slightly different line numbers.

```
TypeError: Cannot read property 'createTask' of undefined
    at Connection.enqueue (/data/rootdir/home/i827087/Projects/Hanamon/node_modules/hdb/lib/protocol/Connection.js:371:30)
    at Connection.fetchNext (/data/rootdir/home/i827087/Projects/Hanamon/node_modules/hdb/lib/protocol/Connection.js:497:8)
    at ResultSet.sendFetch (/data/rootdir/home/i827087/Projects/Hanamon/node_modules/hdb/lib/protocol/ResultSet.js:288:20)
    at ResultSet.resume (/data/rootdir/home/i827087/Projects/Hanamon/node_modules/hdb/lib/protocol/ResultSet.js:135:15)
    at Readable._read (/data/rootdir/home/i827087/Projects/Hanamon/node_modules/hdb/lib/util/index.js:225:8)
    at Readable.read (_stream_readable.js:348:10)
    at flow (_stream_readable.js:761:34)
    at ResultSetTransform.<anonymous> (_stream_readable.js:623:7)
    at emitNone (events.js:86:13)
    at ResultSetTransform.emit (events.js:185:7)
```

**Comment by ktravelet** [comment]
Interesting enough the issue seemed to stop happening.  I'll keep an eye on it and update if anything changes.
